
name = "abandoned-city-pass-creator"

main = "worker.js"

compatibility_date = "2026-08-18"

[assets]
directory = "."
binding = "ASSETS"

[secrets]
required = ["VQkcsRWkTEye1CHaxPRj20BU9iWGj2U8L1AWksMPs1E4OJTgZXlKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNkluTnBaeTB5TURJeExUQTNMVEV6VkRFNE9qVXhPalE1V2lJc0luUjVjQ0k2SWtwWFZDSjkuZXlKaGRXUWlPaUpTYjJKc2IzaEpiblJsY201aGJDSXNJbWx6Y3lJNklrTnNiM1ZrUVhWMGFHVnVkR2xqWVhScGIyNVRaWEoyYVdObElpd2lZbUZ6WlVGd2FVdGxlU0k2SWxaUmEyTnpVbGRyVkVWNVpURkRTR0Y0VUZKcU1qQkNWVGxwVjBkcU1sVTRUREZCVjJ0elRWQnpNVVUwVDBwVVp5SXNJbTkzYm1WeVNXUWlPaUkwTURZek9EYzVNVGt3SWl3aVpYaHdJam94TnpnM01EY3dOemszTENKcFlYUWlPakUzT0Rjd05qY3hPVGNzSW01aVppSTZNVGM0TnpBMk56RTVOMzAuQl9keXFYZWhhZnk5MXdNeHVVME45WW83VU9mWWxlZ1g3MVFhUE9XOUExVTZnMV9IWW1taU93b242S2Y3U3NWVWxsTkFqeVktTDNNeEJRelRlOHU5cS16a2JQdmZLTmJmcHM2VVB3TjdERVUtY3M4SzBFNnoxMHc2dnpiVFhGb3VHNG5KSjFDVGFrQ3JPTDczOWNFSE53ckJ4WEplbzR6eUN5VE1vdUUyWGNBOXN0ajdMeDJuLXItb2JndjZxLTdHRUk3c1FxLWVQOWVpM09yeGlEdkRwSWU4US1JZ0tqWmp3WnRxRWhxMGlDdE5KWldxTkxfeVVFa1prYngzR3dXMG00X28teTZqSGtDeXNrVTBnYUItY2hVWVBFRWF3ZnphWDVoUVFoR2diZFF6bDkzdklYLXFIb1BSZFVpQ00zelQ3VUhGVXI3OUlHXy0wTmF1MEk2c2V3"]

